### PR TITLE
Added a bunch of `follows` to `flake.nix`

### PR DESCRIPTION
**Pull request by jaredponn**
Before this PR:
```
$ time nix flake lock
real	0m1.879s
user	0m1.803s
sys	0m0.068s
$ cat flake.lock | jq '.nodes | keys' | awk -e 'BEGIN { i = 0 } /nixpkgs/ { i++ } END {print i}'
183
```

This PR:
```
$ time nix flake lock

real	0m0.664s
user	0m0.592s
sys	0m0.052s

$ cat flake.lock | jq '.nodes | keys' | awk -e 'BEGIN { i = 0 } /nixpkgs/ { i++ } END {print i }'
106
```

### CODE REVIEW

**Review by bladyjoker — COMMENTED** [review]
Woke up thinking we should do a round on all our repos and do this optimization. THank you!

I also find it very ugly, like knowing how all the inputs name their inputs breaks any notion of abstraction.

**Comment by jaredponn** [comment]
> Woke up thinking we should do a round on all our repos and do this optimization. THank you!

The only remaining major culprit is CTL's db sync which doesn't follow their `haskell-nix`. I'm struggling to try to convince `nix` that it should follow the more recent version (with CTL's haskell.nix), but it's probably better to PR ctl or something to do this instead of me trying to patch this

**Comment by bladyjoker** [comment]
Excellent description in [8ae1013](https://github.com/mlabs-haskell/flake-lang.nix/pull/31/commits/8ae1013fd322097808299777f31a6f9563f3d9b3)

**Comment by jaredponn** [comment]
> Excellent description in [8ae1013](https://github.com/mlabs-haskell/flake-lang.nix/pull/31/commits/8ae1013fd322097808299777f31a6f9563f3d9b3)

I think I'll rebase all the garbage commits lol

**Comment by bladyjoker** [comment]
> > Excellent description in [8ae1013](https://github.com/mlabs-haskell/flake-lang.nix/pull/31/commits/8ae1013fd322097808299777f31a6f9563f3d9b3)
> 
> I think I'll rebase all the garbage commits lol

nonsense, keep it for future generations

**Comment by bladyjoker** [comment]
fyi @jaredponn I'm now setting my repo to use lb and flake-lang from lb, and everything else mostly to follow from that. So if you manage to reduce the flake.lock here, it immediately affects me.

That being said, if you change the inputs then it will break me.

**Comment by jaredponn** [comment]
Alright, I see. I think I'm about to give up for today (maybe tomorrow I'll fork ctl or something just to see if my `db-sync` idea will work cuz I can't get it to work here)..

In https://github.com/mlabs-haskell/lambda-buffers/pull/190, I just added the `follows` stuff to TS and it yields some pretty significant performance gains already, so it might be a good idea to check it out.

**Pull request merged**
